sudo: false
dist: trusty

language: node_js

node_js:
  - "7"
  - "6"
  - "4"

before_install: if [[ `npm -v` != 3* || `npm -v` != 4* ]]; then npm i -g npm@3; fi

addons:
  code_climate:
    repo_token: 185e4d44752c64f89d9e5c50eb3a8d5ec421acf3b58b7cdb01ddcff2257336dd

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
